#httpsListenerConfigurations
https.listener.host=0.0.0.0
https.listener.port=8081
https.listener.basepath=/api/*
https.listener.readTimeout=120000
https.listener.connectionIdleTimeout=40000
https.listener.frequency=2000
https.listener.reconnectionAttempts=2

http.host=0.0.0.0
http.port=8081

employee.http.basepath=/employees
wait.time=2000
anypoint.orgId=34901fc3-b217-4fec-88cd-db41d5f502e8
anypoint.envId=03beaf2a-c843-42fa-8e12-47e987788a59
maxIdleTime=30

reconnection.frequency=3000
reconnection.attempts=3

# Request defaults
requestor.maxcon=-1
requestor.connectionIdTimeOut=60000000
requestor.bufferSize=1024
