### TLS Config ###
tls.keystore.path=tls/awi-int-api-prod_keystore.jks
tls.keystore.type=JKS
tls.truststore.path=tls/awi-int-api_truststore.jks
tls.truststore.type=JKS
tls.context.ref=TLS_Context_HTTPs_Req

servicenow.host=armstrong.service-now.com
servicenow.path=/api/now/table/em_event
servicenow.username=svc_mulesoft

internal.url=-kctxoq.internal-prdhqe.usa-e1.cloudhub.io