### TLS Config ###
tls.keystore.key.password = ![8QcwHAmReicxijvoqznTaA==]
tls.keystore.password = ![8QcwHAmReicxijvoqznTaA==]
tls.truststore.password = ![pCORLt8NaSJjmQYO9pvwpw==]
### SNOW Config ###
servicenow.password=![k+kk6VRH2zLhcSgYsXRPEw==]