### TLS Config ###
tls.keystore.path=tls/awi-int-api-nonprod_keystore.jks
tls.keystore.type=JKS
tls.truststore.path=tls/awi-int-api_truststore.jks
tls.truststore.type=JKS
tls.context.ref=TLS_Context_Insecure

servicenow.host=armstrongtest.service-now.com
servicenow.path=/api/now/table/em_event
servicenow.username=svc_mulesoft

internal.url=-mwonoq.internal-m9no7h.usa-e1.cloudhub.io